language: python
services:
- docker
python:
- '3.6'
install:
- pip install pycodestyle
- pip install mypy mypy-extensions
- pip install --upgrade .
script:
- pycodestyle --show-source specminers
- mypy specminers --ignore-missing-imports
notifications:
  email: false
